### ISSUE TITLE
data for -1 (Not a number)

### ISSUE THREAD

**Issue by devloper13** [FabianGroeger96/cnn-number-detection#15]
Hey I wanted to know how did you decide what the data for -1 should be? Is it random croppings from the image?  If so, will it work if a completely new background is introduced?

**Comment by FabianGroeger96** [comment]
The images for the `-1` class are random cropping from the environment where the model will operate. We collected those images by running a trained model within its environment and checking where it would fail and where it had difficulties distinguishing between a number and other objects. 

The model should, in principle, work if the background is changed, even if the new background isn't yet in the `-1` class. We also tested this with one of our models. It seemed to work reasonably well in a completely new environment. This is mainly because the model learned that everything that didn't exactly match a number was assigned to the class `-1`. Thus, it is also necessary to make sure the "not a number" class is as diverse as possible. Otherwise, you won't get that behaviour.
